// SPDX-License-Identifier: PMPL-1.0-or-later
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function isAvailable() {
  return (typeof globalThis.DOMPurify !== 'undefined' && typeof globalThis.DOMPurify.sanitize === 'function');
}

let defaultConfig_forbidTags = [
  "script",
  "iframe",
  "object",
  "embed",
  "form",
  "base",
  "meta",
  "link",
  "template",
  "math",
  "svg"
];

let defaultConfig_forbidAttr = [
  "onerror",
  "onload",
  "onclick",
  "onmouseover",
  "onfocus",
  "onblur",
  "onsubmit",
  "onchange",
  "oninput",
  "onkeydown",
  "onkeyup",
  "onkeypress",
  "formaction",
  "xlink:href",
  "action"
];

let defaultConfig = {
  forbidTags: defaultConfig_forbidTags,
  forbidAttr: defaultConfig_forbidAttr
};

function sanitize(_html) {
  if (isAvailable()) {
    return (globalThis.DOMPurify.sanitize(_html, {
        FORBID_TAGS: _forbidTags || [],
        FORBID_ATTR: _forbidAttr || [],
        ALLOW_ARIA_ATTR: true,
        ALLOW_DATA_ATTR: false,
        RETURN_DOM: false,
        RETURN_DOM_FRAGMENT: false,
        WHOLE_DOCUMENT: false
      }));
  }
}

function sanitizeWithConfig(_html, cfg) {
  if (isAvailable()) {
    Stdlib_Option.isSome(cfg.allowedTags);
    Stdlib_Option.isSome(cfg.allowedAttr);
    return ((function() {
        var config = {
          FORBID_TAGS: _forbidTags,
          FORBID_ATTR: _forbidAttr,
          ALLOW_ARIA_ATTR: true,
          ALLOW_DATA_ATTR: false,
          RETURN_DOM: false
        };
        if (_hasAllowedTags) config.ALLOWED_TAGS = _allowedTags;
        if (_hasAllowedAttr) config.ALLOWED_ATTR = _allowedAttr;
        return globalThis.DOMPurify.sanitize(_html, config);
      })());
  }
}

function version() {
  if (isAvailable()) {
    return (globalThis.DOMPurify.version || "unknown");
  }
}

export {
  isAvailable,
  defaultConfig,
  sanitize,
  sanitizeWithConfig,
  version,
}
/* No side effect */
