// SPDX-License-Identifier: PMPL-1.0-or-later
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DOMPurify from "./DOMPurify.res.js";
import * as TrustedTypes from "./TrustedTypes.res.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let logRef = {
  contents: []
};

function nowMs() {
  return (typeof performance !== 'undefined' && typeof performance.now === 'function' ? performance.now() : Date.now());
}

function appendEntry(entry) {
  logRef.contents = logRef.contents.concat([entry]);
}

function record(event, detail) {
  appendEntry({
    event: event,
    detail: detail,
    timestampMs: nowMs()
  });
}

function entries() {
  return logRef.contents;
}

function latest() {
  let current = logRef.contents;
  let len = current.length;
  if (len === 0) {
    return;
  } else {
    return current[len - 1 | 0];
  }
}

function clear() {
  logRef.contents = [];
}

function snapshot() {
  return logRef.contents;
}

function count() {
  return logRef.contents.length;
}

function filterByPrefix(prefix) {
  return logRef.contents.filter(e => e.event.startsWith(prefix));
}

let MountTracer = {
  logRef: logRef,
  nowMs: nowMs,
  appendEntry: appendEntry,
  record: record,
  entries: entries,
  latest: latest,
  clear: clear,
  snapshot: snapshot,
  count: count,
  filterByPrefix: filterByPrefix
};

function trim(s) {
  return s.trim();
}

function length(s) {
  return s.length;
}

let SafeString = {
  trim: trim,
  length: length
};

let invalidSelectorRegex = /[^\w\-#\.\[\]():>~+= \"',*]/g;

function recordOutcome(selector, outcome) {
  let detail;
  detail = outcome.TAG === "Ok" ? "selector valid" : outcome._0;
  record("selector-validation", selector + ";" + detail);
}

function validate(selector) {
  let trimmed = selector.trim();
  let len = trimmed.length;
  let outcome = len === 0 ? ({
      TAG: "Error",
      _0: "Selector cannot be empty"
    }) : (
      len > 255 ? ({
          TAG: "Error",
          _0: "Selector exceeds maximum length (255 characters)"
        }) : (
          invalidSelectorRegex.test(trimmed) ? (invalidSelectorRegex.lastIndex = 0, {
              TAG: "Error",
              _0: "Selector contains invalid CSS characters"
            }) : (invalidSelectorRegex.lastIndex = 0, {
              TAG: "Ok",
              _0: {
                TAG: "ValidSelector",
                _0: trimmed
              }
            })
        )
    );
  recordOutcome(trimmed, outcome);
  return outcome;
}

function toString(value) {
  return value._0;
}

let ProvenSelector = {
  invalidSelectorRegex: invalidSelectorRegex,
  recordOutcome: recordOutcome,
  validate: validate,
  toString: toString
};

function recordOutcome$1(html, outcome, method) {
  let detail;
  detail = outcome.TAG === "Ok" ? "html valid" : outcome._0;
  let methodStr;
  switch (method) {
    case "DOMPurifyMethod" :
      methodStr = "dompurify";
      break;
    case "RegexFallback" :
      methodStr = "regex-fallback";
      break;
    case "DualLayer" :
      methodStr = "dual-layer";
      break;
  }
  let summary = "size=" + html.length.toString() + ";method=" + methodStr;
  record("html-validation", summary + ";" + detail);
}

function regexSanitise(html) {
  return html.replace(/<script[^>]*>[\s\S]*?<\/script>/gi, "").replace(/<iframe[^>]*>[\s\S]*?<\/iframe>/gi, "").replace(/<object[^>]*>[\s\S]*?<\/object>/gi, "").replace(/<embed[^>]*>[\s\S]*?<\/embed>/gi, "").replace(/<form[^>]*>[\s\S]*?<\/form>/gi, "").replace(/<math[^>]*>[\s\S]*?<\/math>/gi, "").replace(/<svg[^>]*>[\s\S]*?<\/svg>/gi, "").replace(/<template[^>]*>[\s\S]*?<\/template>/gi, "").replace(/<script[^>]*\/?>/gi, "").replace(/<iframe[^>]*\/?>/gi, "").replace(/<object[^>]*\/?>/gi, "").replace(/<embed[^>]*\/?>/gi, "").replace(/<base[^>]*\/?>/gi, "").replace(/<link[^>]*\/?>/gi, "").replace(/<meta[^>]*http-equiv[^>]*\/?>/gi, "").replace(/\s+on\w+\s*=\s*[\"'][^\"']*[\"']/gi, "").replace(/\s+on\w+\s*=\s*[^\s>]+/gi, "").replace(/\s+formaction\s*=\s*[\"'][^\"']*[\"']/gi, "").replace(/\s+formaction\s*=\s*[^\s>]+/gi, "").replace(/\s+xlink:href\s*=\s*[\"'][^\"']*[\"']/gi, "").replace(/\s+srcdoc\s*=\s*[\"'][^\"']*[\"']/gi, "").replace(/javascript\s*:/gi, "blocked:").replace(/vbscript\s*:/gi, "blocked:").replace(/\s+(src|href|action)\s*=\s*[\"']data:[^\"']*[\"']/gi, "").replace(/style\s*=\s*[\"'][^\"']*url\s*\([^)]*\)[^\"']*[\"']/gi, "");
}

function sanitise(html) {
  let purified = DOMPurify.sanitize(html);
  if (purified !== undefined) {
    let doubleSanitised = regexSanitise(purified);
    return [
      doubleSanitised,
      "DualLayer"
    ];
  }
  let sanitised = regexSanitise(html);
  return [
    sanitised,
    "RegexFallback"
  ];
}

let voidElements = [
  "area",
  "base",
  "br",
  "col",
  "embed",
  "hr",
  "img",
  "input",
  "link",
  "meta",
  "param",
  "source",
  "track",
  "wbr"
];

function isVoidElement(name) {
  return voidElements.includes(name.toLowerCase());
}

function checkTagNesting(_html) {
  let nestingResult = ((function() {
        var voids = ["area","base","br","col","embed","hr","img","input","link","meta","param","source","track","wbr"];
        var re = /<\/?([a-zA-Z][a-zA-Z0-9]*)[^>]*\/?>/g;
        var stack = [];
        var match;
        while ((match = re.exec(_html)) !== null) {
          var full = match[0];
          var tag = match[1].toLowerCase();
          if (voids.indexOf(tag) !== -1) continue;
          if (full.charAt(1) === '/') {
            // Closing tag
            if (stack.length === 0) return 'Unexpected closing tag </' + tag + '> with no matching open tag';
            var top = stack[stack.length - 1];
            if (top !== tag) return 'Misnested tags: expected </' + top + '> but found </' + tag + '>';
            stack.pop();
          } else if (full.charAt(full.length - 2) === '/') {
            // Self-closing — skip
          } else {
            stack.push(tag);
          }
        }
        if (stack.length > 0) return 'Unclosed tags: ' + stack.join(', ');
        return null;
      })());
  if (nestingResult == null) {
    return {
      TAG: "Ok",
      _0: undefined
    };
  } else {
    return {
      TAG: "Error",
      _0: nestingResult
    };
  }
}

function validate$1(html) {
  let match = sanitise(html);
  let sanitised = match[0];
  let len = sanitised.length;
  let outcome;
  if (len > 1048576) {
    outcome = {
      TAG: "Error",
      _0: "HTML content exceeds maximum size (1MB)"
    };
  } else {
    let nestingError = checkTagNesting(sanitised);
    outcome = nestingError.TAG === "Ok" ? ({
        TAG: "Ok",
        _0: {
          TAG: "ValidHTML",
          _0: sanitised
        }
      }) : ({
        TAG: "Error",
        _0: nestingError._0
      });
  }
  recordOutcome$1(sanitised, outcome, match[1]);
  return outcome;
}

function toString$1(value) {
  return value._0;
}

let ProvenHTML = {
  maxSize: 1048576,
  recordOutcome: recordOutcome$1,
  regexSanitise: regexSanitise,
  sanitise: sanitise,
  voidElements: voidElements,
  isVoidElement: isVoidElement,
  checkTagNesting: checkTagNesting,
  validate: validate$1,
  toString: toString$1
};

function initTrustedTypes() {
  let result = TrustedTypes.init();
  if (result) {
    record("trusted-types-init", "safe-dom policy created");
  } else if (TrustedTypes.isSupported()) {
    record("trusted-types-init", "policy already exists or creation failed");
  } else {
    record("trusted-types-init", "browser does not support Trusted Types");
  }
  return result;
}

function findMountPoint(selector) {
  return Primitive_option.fromNullable((document.querySelector(_selectorStr)));
}

function mount(selector, html) {
  let selectorStr = selector._0;
  let htmlStr = html._0;
  record("mount-attempt", "selector=" + selectorStr);
  let element = findMountPoint(selector);
  if (element !== undefined) {
    if (TrustedTypes.hasPolicy()) {
      TrustedTypes.createHTML(htmlStr);
      ((element.innerHTML = _trusted));
      record("mount-method", "trusted-types");
    } else {
      ((element.innerHTML = _htmlStr));
      record("mount-method", "direct-string");
    }
    let id = element.id;
    let identity = id === "" ? "anonymous" : id;
    record("mount-success", "selector=" + selectorStr + ";element=" + identity);
    return {
      TAG: "Mounted",
      _0: Primitive_option.valFromOption(element)
    };
  }
  record("mount-failure", "selector=" + selectorStr + ";reason=mount-point-missing");
  return {
    TAG: "MountPointNotFound",
    _0: selectorStr
  };
}

function mountParsed(selector, html) {
  let selectorStr = selector._0;
  record("mount-parsed-attempt", "selector=" + selectorStr);
  let element = findMountPoint(selector);
  if (element !== undefined) {
    (((function() {
        var parser = new DOMParser();
        var doc = parser.parseFromString(_htmlStr, 'text/html');
        element.innerHTML = '';
        var body = doc.body;
        while (body.firstChild) {
          element.appendChild(body.firstChild);
        }
      })()));
    let id = element.id;
    let identity = id === "" ? "anonymous" : id;
    record("mount-parsed-success", "selector=" + selectorStr + ";element=" + identity + ";method=domparser");
    return {
      TAG: "Mounted",
      _0: Primitive_option.valFromOption(element)
    };
  }
  record("mount-parsed-failure", "selector=" + selectorStr + ";reason=mount-point-missing");
  return {
    TAG: "MountPointNotFound",
    _0: selectorStr
  };
}

function mountString(selector, html) {
  let e = validate(selector);
  if (e.TAG !== "Ok") {
    return {
      TAG: "InvalidSelector",
      _0: e._0
    };
  }
  let e$1 = validate$1(html);
  if (e$1.TAG === "Ok") {
    return mount(e._0, e$1._0);
  } else {
    return {
      TAG: "InvalidHTML",
      _0: e$1._0
    };
  }
}

function mountStringParsed(selector, html) {
  let e = validate(selector);
  if (e.TAG !== "Ok") {
    return {
      TAG: "InvalidSelector",
      _0: e._0
    };
  }
  let e$1 = validate$1(html);
  if (e$1.TAG === "Ok") {
    return mountParsed(e._0, e$1._0);
  } else {
    return {
      TAG: "InvalidHTML",
      _0: e$1._0
    };
  }
}

function mountSafe(selector, html, onSuccess, onError) {
  let el = mountString(selector, html);
  switch (el.TAG) {
    case "Mounted" :
      return onSuccess(el._0);
    case "MountPointNotFound" :
      return onError(`Mount point not found: ` + el._0);
    case "InvalidSelector" :
      return onError(`Invalid selector: ` + el._0);
    case "InvalidHTML" :
      return onError(`Invalid HTML: ` + el._0);
  }
}

function mountBatch(specs) {
  let validatedSpecs = specs.map(spec => {
    let e = validate(spec.selector);
    if (e.TAG !== "Ok") {
      return {
        TAG: "Error",
        _0: `Selector validation failed for "` + spec.selector + `": ` + e._0
      };
    }
    let e$1 = validate$1(spec.html);
    if (e$1.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: [
          e._0,
          e$1._0
        ]
      };
    } else {
      return {
        TAG: "Error",
        _0: `HTML validation failed for "` + spec.selector + `": ` + e$1._0
      };
    }
  });
  let firstError = validatedSpecs.find(spec => spec.TAG !== "Ok");
  if (firstError !== undefined && firstError.TAG !== "Ok") {
    let err = firstError._0;
    record("batch-mount-validation-failure", err);
    return {
      TAG: "Error",
      _0: err
    };
  }
  let elements = [];
  let error = {
    contents: undefined
  };
  validatedSpecs.forEach(spec => {
    if (!Stdlib_Option.isNone(error.contents)) {
      return;
    }
    if (spec.TAG !== "Ok") {
      return;
    }
    let match = spec._0;
    let el = mount(match[0], match[1]);
    switch (el.TAG) {
      case "Mounted" :
        elements.push(el._0);
        return;
      case "MountPointNotFound" :
        let msg = `Batch mount failed: ` + el._0;
        record("batch-mount-failure", msg);
        error.contents = msg;
        return;
      case "InvalidSelector" :
        let msg$1 = `Batch mount invalid selector: ` + el._0;
        record("batch-mount-failure", msg$1);
        error.contents = msg$1;
        return;
      case "InvalidHTML" :
        let msg$2 = `Batch mount invalid HTML: ` + el._0;
        record("batch-mount-failure", msg$2);
        error.contents = msg$2;
        return;
    }
  });
  let err$1 = error.contents;
  if (err$1 !== undefined) {
    return {
      TAG: "Error",
      _0: err$1
    };
  } else {
    record("batch-mount-success", "count=" + elements.length.toString());
    return {
      TAG: "Ok",
      _0: elements
    };
  }
}

function onDOMReady(callback) {
  record("dom-ready-check", "scheduling");
  let readyState = document.readyState;
  if (readyState === "complete" || readyState === "interactive") {
    return callback();
  } else {
    ((document.addEventListener('DOMContentLoaded', callback)));
    return record("dom-ready-listen", "waiting for DOMContentLoaded");
  }
}

function mountWhenReady(selector, html, onSuccess, onError) {
  onDOMReady(() => mountSafe(selector, html, onSuccess, onError));
}

function unmount(selector) {
  let s = selector._0;
  record("unmount_attempt", s);
  let el = findMountPoint(selector);
  if (el !== undefined) {
    ((element.innerHTML = ""));
    record("unmount_success", s);
    return {
      TAG: "Mounted",
      _0: Primitive_option.valFromOption(el)
    };
  } else {
    record("unmount_not_found", s);
    return {
      TAG: "MountPointNotFound",
      _0: s
    };
  }
}

function remount(selector, html) {
  let e = validate(selector);
  if (e.TAG !== "Ok") {
    return {
      TAG: "InvalidSelector",
      _0: e._0
    };
  }
  let validSelector = e._0;
  let e$1 = validate$1(html);
  if (e$1.TAG !== "Ok") {
    return {
      TAG: "InvalidHTML",
      _0: e$1._0
    };
  }
  unmount(validSelector);
  return mount(validSelector, e$1._0);
}

function mountWithNonce(selector, html, nonce) {
  let e = validate(selector);
  if (e.TAG !== "Ok") {
    return {
      TAG: "InvalidSelector",
      _0: e._0
    };
  }
  let noncedHtml = html.replace(/<style/gi, `<style nonce="` + nonce + `"`);
  let e$1 = validate$1(noncedHtml);
  if (e$1.TAG !== "Ok") {
    return {
      TAG: "InvalidHTML",
      _0: e$1._0
    };
  }
  record("mount_with_nonce", nonce);
  return mount(e._0, e$1._0);
}

function safetyDiagnostics() {
  return {
    dompurifyAvailable: DOMPurify.isAvailable(),
    dompurifyVersion: DOMPurify.version(),
    trustedTypesSupported: TrustedTypes.isSupported(),
    trustedTypesPolicyActive: TrustedTypes.hasPolicy(),
    regexSanitiserActive: true,
    stackBasedNesting: true,
    traceEntryCount: logRef.contents.length
  };
}

export {
  MountTracer,
  SafeString,
  ProvenSelector,
  ProvenHTML,
  initTrustedTypes,
  findMountPoint,
  mount,
  mountParsed,
  mountString,
  mountStringParsed,
  mountSafe,
  mountBatch,
  onDOMReady,
  mountWhenReady,
  unmount,
  remount,
  mountWithNonce,
  safetyDiagnostics,
}
/* No side effect */
