// SPDX-License-Identifier: PMPL-1.0-or-later
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function isSupported() {
  return (typeof globalThis.trustedTypes !== 'undefined' && typeof globalThis.trustedTypes.createPolicy === 'function');
}

let policyRef = {
  contents: undefined
};

function init() {
  let match = policyRef.contents;
  if (match !== undefined) {
    return false;
  }
  if (!isSupported()) {
    return false;
  }
  let _policy = (globalThis.trustedTypes.createPolicy('safe-dom', {
          createHTML: function(input) {
            // If DOMPurify is available, sanitise through it.
            // Otherwise trust the caller (SafeDOMCore pre-sanitises).
            if (typeof globalThis.DOMPurify !== 'undefined') {
              return globalThis.DOMPurify.sanitize(input, {
                RETURN_TRUSTED_TYPE: true,
                FORBID_TAGS: ['script', 'iframe', 'object', 'embed', 'form', 'base', 'meta', 'link', 'template', 'math', 'svg'],
                FORBID_ATTR: ['onerror', 'onload', 'onclick', 'onmouseover', 'onfocus', 'onblur', 'onsubmit', 'onchange', 'oninput', 'onkeydown', 'onkeyup', 'onkeypress', 'formaction', 'xlink:href', 'action']
              });
            }
            return input;
          },
          createScript: function() {
            // Block all script creation through Trusted Types
            throw new Error('safe-dom policy: script creation is blocked');
          },
          createScriptURL: function() {
            // Block all script URL creation through Trusted Types
            throw new Error('safe-dom policy: script URL creation is blocked');
          }
        }));
  policyRef.contents = Primitive_option.some(_policy);
  return true;
}

function createHTML(html) {
  let _policy = policyRef.contents;
  if (_policy !== undefined) {
    return (_policy.createHTML(html));
  } else {
    return html;
  }
}

function toString(_trusted) {
  return (String(_trusted));
}

function hasPolicy() {
  return Stdlib_Option.isSome(policyRef.contents);
}

export {
  isSupported,
  policyRef,
  init,
  createHTML,
  toString,
  hasPolicy,
}
/* No side effect */
