// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SafeDOMCore from "./Core/SafeDOMCore.res.js";

let Core;

let Purify;

let TrustedTypes;

let initTrustedTypes = SafeDOMCore.initTrustedTypes;

let mount = SafeDOMCore.mount;

let mountParsed = SafeDOMCore.mountParsed;

let mountString = SafeDOMCore.mountString;

let mountStringParsed = SafeDOMCore.mountStringParsed;

let mountSafe = SafeDOMCore.mountSafe;

let mountBatch = SafeDOMCore.mountBatch;

let onDOMReady = SafeDOMCore.onDOMReady;

let mountWhenReady = SafeDOMCore.mountWhenReady;

let unmount = SafeDOMCore.unmount;

let remount = SafeDOMCore.remount;

let mountWithNonce = SafeDOMCore.mountWithNonce;

let safetyDiagnostics = SafeDOMCore.safetyDiagnostics;

export {
  Core,
  Purify,
  TrustedTypes,
  initTrustedTypes,
  mount,
  mountParsed,
  mountString,
  mountStringParsed,
  mountSafe,
  mountBatch,
  onDOMReady,
  mountWhenReady,
  unmount,
  remount,
  mountWithNonce,
  safetyDiagnostics,
}
/* No side effect */
